version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    ports:
      - "${API_PORT}:${API_PORT}"
    command: npm run dev
  planner-database:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    container_name: planner-database
    logging:
      driver: none
