version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    command: npm run dev
    networks:
      - planner_default
  database:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:${MYSQL_PORT}
    container_name: database
    logging:
      driver: none
    networks:
      - planner_default
networks:
  planner_default:
    driver: bridge
