version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    command: npm run dev
